### ISSUE TITLE
Binary messages

### ISSUE THREAD

**Issue by OTL** [void-dragon/nanomsg-browser#1]
Current implementation cannot deal binary data because it uses 'readAsText()' to read the data.
(There are same problem in 'send()' because it uses 'charCodeAt()')

What do you think?
Is it reasonable to add option to use binary data, like below?

```js
nanomsg.binary = true
```

**Comment by void-dragon** [comment]
Well i added a feature flag: `nanomsg.receiveArrayBuffer = true;`
If it is enabled you receive ArrayBuffer objects instead of strings.
In the case of sending, the send call should now be able to recognize if you provide a String or a ArrayBuffer object.
Please checkout the master branch and look if it is working for you,

**Comment by OTL** [comment]
Sounds great!

I'll test it in a few days.

**Comment by OTL** [comment]
Receive works fine! Thank you!

But it seems that binary send has a bug.

It needs `msg = data` around L170, if it sends `msg`.

**Comment by OTL** [comment]
I created #2. You can use it if you want.

**Comment by void-dragon** [comment]
Lol i see the error now. But your pull request will not work for none REQ sockets. Let me fix this typo.

**Comment by OTL** [comment]
Thank you for your kindness!

**Comment by void-dragon** [comment]
Thank you for pointing out the issue :)
